from django.urls import path

from apps.platform_admin.views import (
    platform_clients_saas_command_center_api,
    platform_command_center_api,
    platform_dashboard_api,
    platform_hotel_admin_create_api,
    platform_hotel_detail_api,
    platform_hotels_dashboard_api,
    platform_hotel_reactivate_api,
    platform_hotel_suspend_api,
    platform_hotels_api,
    platform_license_detail_api,
    platform_license_renew_api,
    platform_license_suspend_api,
    platform_licenses_api,
    platform_module_access_check_api,
    platform_module_detail_api,
    platform_modules_command_center_api,
    platform_modules_api,
    platform_onboarding_bundle_api,
    platform_organization_detail_api,
    platform_organizations_api,
    platform_security_review_api,
    platform_security_events_api,
    platform_subscription_change_plan_api,
    platform_subscription_detail_api,
    platform_subscription_lifecycle_run_api,
    platform_subscription_plan_detail_api,
    platform_subscription_plans_api,
    platform_subscription_renew_api,
    platform_subscriptions_api,
    platform_user_activate_api,
    platform_user_deactivate_api,
    platform_user_detail_api,
    platform_user_reset_access_api,
    platform_users_api,
)


urlpatterns = [
    path("command-center/", platform_command_center_api, name="api-platform-command-center"),
    path("dashboard/", platform_dashboard_api, name="api-platform-dashboard"),
    path("onboarding/", platform_onboarding_bundle_api, name="api-platform-onboarding"),
    path("organizations/", platform_organizations_api, name="api-platform-organizations"),
    path("clients-saas/command-center/", platform_clients_saas_command_center_api, name="api-platform-clients-saas-command-center"),
    path("organizations/<int:organization_id>/", platform_organization_detail_api, name="api-platform-organization-detail"),
    path("hotels/", platform_hotels_api, name="api-platform-hotels"),
    path("hotels/dashboard/", platform_hotels_dashboard_api, name="api-platform-hotels-dashboard"),
    path("hotels/<int:hotel_id>/", platform_hotel_detail_api, name="api-platform-hotel-detail"),
    path("hotels/<int:hotel_id>/admin/", platform_hotel_admin_create_api, name="api-platform-hotel-admin-create"),
    path("hotels/<int:hotel_id>/suspend/", platform_hotel_suspend_api, name="api-platform-hotel-suspend"),
    path("hotels/<int:hotel_id>/reactivate/", platform_hotel_reactivate_api, name="api-platform-hotel-reactivate"),
    path("subscriptions/", platform_subscriptions_api, name="api-platform-subscriptions"),
    path("subscriptions/process-lifecycle/", platform_subscription_lifecycle_run_api, name="api-platform-subscription-lifecycle-run"),
    path("subscriptions/plans/", platform_subscription_plans_api, name="api-platform-subscription-plans"),
    path("subscriptions/plans/<int:plan_id>/", platform_subscription_plan_detail_api, name="api-platform-subscription-plan-detail"),
    path("subscriptions/<int:subscription_id>/", platform_subscription_detail_api, name="api-platform-subscription-detail"),
    path("subscriptions/<int:subscription_id>/renew/", platform_subscription_renew_api, name="api-platform-subscription-renew"),
    path("subscriptions/<int:subscription_id>/change-plan/", platform_subscription_change_plan_api, name="api-platform-subscription-change-plan"),
    path("modules/", platform_modules_api, name="api-platform-modules"),
    path("modules/command-center/", platform_modules_command_center_api, name="api-platform-modules-command-center"),
    path("modules/check-access/", platform_module_access_check_api, name="api-platform-module-access-check"),
    path("modules/<int:module_id>/", platform_module_detail_api, name="api-platform-module-detail"),
    path("licenses/", platform_licenses_api, name="api-platform-licenses"),
    path("licenses/<int:license_id>/", platform_license_detail_api, name="api-platform-license-detail"),
    path("licenses/<int:license_id>/suspend/", platform_license_suspend_api, name="api-platform-license-suspend"),
    path("licenses/<int:license_id>/renew/", platform_license_renew_api, name="api-platform-license-renew"),
    path("users/", platform_users_api, name="api-platform-users"),
    path("users/<int:user_id>/", platform_user_detail_api, name="api-platform-user-detail"),
    path("users/<int:user_id>/activate/", platform_user_activate_api, name="api-platform-user-activate"),
    path("users/<int:user_id>/deactivate/", platform_user_deactivate_api, name="api-platform-user-deactivate"),
    path("users/<int:user_id>/reset-access/", platform_user_reset_access_api, name="api-platform-user-reset-access"),
    path("security-events/", platform_security_events_api, name="api-platform-security-events"),
    path("security-events/review/", platform_security_review_api, name="api-platform-security-review"),
]
