from django.urls import path

from apps.operations.api_views import (
    booking_check_in_api,
    booking_detail_api,
    bookings_list_api,
    bulk_booking_check_in_api,
    bulk_complete_cleaning_api,
    bulk_day_use_check_in_api,
    bulk_day_use_check_out_api,
    bulk_stay_check_out_api,
    cancel_booking_api,
    cancel_payment_api,
    complete_room_cleaning_api,
    confirm_booking_api,
    create_booking_api,
    create_day_use_api,
    create_payment_api,
    create_stay_api,
    day_use_check_in_api,
    day_use_check_out_api,
    day_use_detail_api,
    day_uses_list_api,
    all_operations_api,
    mark_booking_no_show_api,
    operations_board_api,
    operations_choices_api,
    payment_detail_api,
    payments_list_api,
    refund_payment_api,
    relocate_booking_api,
    relocate_stay_api,
    stay_check_out_api,
    stay_detail_api,
    stays_list_api,
    update_booking_api,
    update_day_use_api,
    update_payment_api,
    update_stay_api,
)
from apps.operations.views.planning_views import planning_api


urlpatterns = [
    path("choices/", operations_choices_api, name="api-operations-choices"),
    path("board/", operations_board_api, name="api-operations-board"),
    path("planning/", planning_api, name="api-operations-planning"),
    path("bulk/bookings/check-in/", bulk_booking_check_in_api, name="api-bulk-booking-check-in"),
    path("bulk/stays/check-out/", bulk_stay_check_out_api, name="api-bulk-stay-check-out"),
    path("bulk/day-uses/check-in/", bulk_day_use_check_in_api, name="api-bulk-day-use-check-in"),
    path("bulk/day-uses/check-out/", bulk_day_use_check_out_api, name="api-bulk-day-use-check-out"),
    path("bulk/rooms/complete-cleaning/", bulk_complete_cleaning_api, name="api-bulk-complete-cleaning"),
    path("all/", all_operations_api, name="api-operations-all"),
    path("bookings/", bookings_list_api, name="api-operations-bookings"),
    path("bookings/<int:booking_id>/", booking_detail_api, name="api-booking-detail"),
    path("bookings/create/", create_booking_api, name="api-create-booking"),
    path("bookings/<int:booking_id>/update/", update_booking_api, name="api-update-booking"),
    path("bookings/<int:booking_id>/confirm/", confirm_booking_api, name="api-confirm-booking"),
    path("bookings/<int:booking_id>/cancel/", cancel_booking_api, name="api-cancel-booking"),
    path("bookings/<int:booking_id>/no-show/", mark_booking_no_show_api, name="api-booking-no-show"),
    path("bookings/<int:booking_id>/check-in/", booking_check_in_api, name="api-booking-check-in"),
    path("bookings/<int:booking_id>/relocate/", relocate_booking_api, name="api-relocate-booking"),
    path("stays/", stays_list_api, name="api-operations-stays"),
    path("stays/create/", create_stay_api, name="api-create-stay"),
    path("stays/<int:stay_id>/", stay_detail_api, name="api-stay-detail"),
    path("stays/<int:stay_id>/update/", update_stay_api, name="api-update-stay"),
    path("stays/<int:stay_id>/check-out/", stay_check_out_api, name="api-stay-check-out"),
    path("stays/<int:stay_id>/relocate/", relocate_stay_api, name="api-relocate-stay"),
    path("day-uses/", day_uses_list_api, name="api-operations-day-uses"),
    path("day-uses/<int:day_use_id>/", day_use_detail_api, name="api-day-use-detail"),
    path("day-uses/<int:day_use_id>/update/", update_day_use_api, name="api-update-day-use"),
    path("day-use/create/", create_day_use_api, name="api-create-day-use"),
    path("day-use/<int:day_use_id>/check-in/", day_use_check_in_api, name="api-day-use-check-in"),
    path("day-use/<int:day_use_id>/check-out/", day_use_check_out_api, name="api-day-use-check-out"),
    path("payments/", payments_list_api, name="api-operations-payments"),
    path("payments/<int:payment_id>/", payment_detail_api, name="api-payment-detail"),
    path("payments/<int:payment_id>/update/", update_payment_api, name="api-update-payment"),
    path("payments/<int:payment_id>/refund/", refund_payment_api, name="api-refund-payment"),
    path("payments/<int:payment_id>/cancel/", cancel_payment_api, name="api-cancel-payment"),
    path("payments/create/", create_payment_api, name="api-create-payment"),
    path("rooms/<int:room_id>/complete-cleaning/", complete_room_cleaning_api, name="api-complete-room-cleaning"),
]
