# Generated by Django 5.2.13 on 2026-04-22 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_dayuse'),
        ('guests', '0004_guest_client_type_guest_document_expiry_date_and_more'),
        ('rooms', '0001_initial'),
        ('stays', '0002_stay_check_out_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='actual_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in reel'),
        ),
        migrations.AddField(
            model_name='stay',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out reel'),
        ),
        migrations.AddField(
            model_name='stay',
            name='adults_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Adultes (detail)'),
        ),
        migrations.AddField(
            model_name='stay',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_stays', to=settings.AUTH_USER_MODEL, verbose_name='Check-in par'),
        ),
        migrations.AddField(
            model_name='stay',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_stays', to=settings.AUTH_USER_MODEL, verbose_name='Check-out par'),
        ),
        migrations.AddField(
            model_name='stay',
            name='children_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Enfants (detail)'),
        ),
        migrations.AddField(
            model_name='stay',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, verbose_name="Nombre d'occupants"),
        ),
        migrations.AddField(
            model_name='stay',
            name='planned_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in prevu'),
        ),
        migrations.AddField(
            model_name='stay',
            name='planned_check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out prevu'),
        ),
        migrations.AddField(
            model_name='stay',
            name='purpose_of_stay',
            field=models.CharField(blank=True, max_length=100, verbose_name='Motif du sejour'),
        ),
        migrations.AddField(
            model_name='stay',
            name='source',
            field=models.CharField(choices=[('booking', 'Reservation'), ('walk_in', 'Walk-in'), ('phone', 'Telephone'), ('website', 'Site web'), ('ota', 'OTA'), ('manual', 'Saisie directe'), ('other', 'Autre')], default='manual', max_length=20, verbose_name='Origine'),
        ),
        migrations.AddField(
            model_name='stay',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Demandes speciales'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='in_progress', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['status', 'room'], name='stay_status_room_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['status', 'guest'], name='stay_status_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['planned_check_in'], name='stay_planned_check_in_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['planned_check_out'], name='stay_planned_check_out_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_guests__gte', 1)), name='stay_at_least_one_guest'),
        ),
    ]
