# Generated by Django 5.2.13 on 2026-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_stay_remove_adults_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='adults_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Adultes'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='children_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Enfants'),
        ),
    ]
