# Generated by Django 5.2.13 on 2026-04-24 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_room_codes_and_day_use_prices(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")
    RoomType = apps.get_model("rooms", "RoomType")

    for room_type in RoomType.objects.filter(base_price_day_use=0):
        room_type.base_price_day_use = room_type.base_price_per_night
        room_type.save(update_fields=["base_price_day_use"])

    for room in Room.objects.select_related("hotel").all():
        hotel_code = getattr(room.hotel, "code", "") or "HOT"
        room_code = f"{hotel_code}-RM-{room.number}".upper()
        Room.objects.filter(pk=room.pk, room_code="").update(room_code=room_code)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_hotel_room_hotel'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('turnover', 'Rotation'), ('deep_cleaning', 'Nettoyage profond'), ('inspection', 'Inspection'), ('touch_up', 'Retouche')], default='turnover', max_length=20, verbose_name='Type de tache')),
                ('status', models.CharField(choices=[('pending', 'A nettoyer'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorite')),
                ('estimated_minutes', models.PositiveIntegerField(default=30, verbose_name='Temps estime (min)')),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temps reel (min)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('issue_reported', models.TextField(blank=True, verbose_name='Probleme signale')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Demande le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Commence le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Termine le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': 'Tache housekeeping',
                'verbose_name_plural': 'Taches housekeeping',
                'ordering': ['status', '-priority', '-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenanceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Severite')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Resolue'), ('closed', 'Cloturee')], default='open', max_length=20, verbose_name='Statut')),
                ('marks_room_out_of_service', models.BooleanField(default=True, verbose_name='Mettre hors service')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Signale le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolue le')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': 'Incident chambre',
                'verbose_name_plural': 'Incidents chambres',
                'ordering': ['status', '-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomRateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('applies_to', models.CharField(choices=[('night', 'Nuit'), ('day_use', 'Day use'), ('both', 'Les deux')], default='night', max_length=20, verbose_name="S'applique a")),
                ('rule_type', models.CharField(choices=[('weekend', 'Week-end'), ('seasonal', 'Saisonnier'), ('occupancy', 'Occupation')], max_length=20, verbose_name='Type de regle')),
                ('adjustment_mode', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percent', max_length=20, verbose_name="Mode d'ajustement")),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('min_occupancy_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Occupation minimum (%)')),
                ('priority', models.PositiveSmallIntegerField(default=10, verbose_name='Priorite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': 'Regle tarifaire chambre',
                'verbose_name_plural': 'Regles tarifaires chambres',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='custom_price_day_use',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif day use personnalise'),
        ),
        migrations.AddField(
            model_name='room',
            name='custom_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif nuit personnalise'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_vip_preferred',
            field=models.BooleanField(default=False, verbose_name='Prioritaire VIP'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier nettoyage'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_inspected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Derniere inspection'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Code chambre'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.JSONField(blank=True, default=list, verbose_name='Equipements'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='base_price_day_use',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de base day use'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_day_use_available',
            field=models.BooleanField(default=True, verbose_name='Day use autorise'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='pricing_policy_notes',
            field=models.TextField(blank=True, verbose_name='Politique tarifaire'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupee'), ('reserved', 'Reservee'), ('cleaning', 'En nettoyage'), ('out_of_service', 'Hors service')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'floor'], name='room_hotel_floor_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'is_active'], name='room_hotel_active_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['hotel', 'is_active'], name='room_type_hotel_active_idx'),
        ),
        migrations.AddField(
            model_name='roomhousekeepingtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_housekeeping_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Attribue a'),
        ),
        migrations.AddField(
            model_name='roomhousekeepingtask',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='housekeeping_tasks', to='tenancy.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='roomhousekeepingtask',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='rooms.room', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='roommaintenanceincident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_room_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Attribue a'),
        ),
        migrations.AddField(
            model_name='roommaintenanceincident',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_maintenance_incidents', to='tenancy.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='roommaintenanceincident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_room_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Signale par'),
        ),
        migrations.AddField(
            model_name='roommaintenanceincident',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_incidents', to='rooms.room', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='roomraterule',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_rate_rules', to='tenancy.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='roomraterule',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='rooms.roomtype', verbose_name='Type de chambre'),
        ),
        migrations.RunPython(backfill_room_codes_and_day_use_prices, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='roomhousekeepingtask',
            index=models.Index(fields=['hotel', 'status'], name='room_hk_hotel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roomhousekeepingtask',
            index=models.Index(fields=['hotel', 'priority'], name='room_hk_hotel_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='roomhousekeepingtask',
            index=models.Index(fields=['hotel', 'assigned_to'], name='room_hk_hotel_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='roommaintenanceincident',
            index=models.Index(fields=['hotel', 'status'], name='room_incident_hotel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roommaintenanceincident',
            index=models.Index(fields=['hotel', 'severity'], name='rm_inc_hotel_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='roommaintenanceincident',
            index=models.Index(fields=['hotel', 'room'], name='rm_inc_hotel_room_idx'),
        ),
        migrations.AddIndex(
            model_name='roomraterule',
            index=models.Index(fields=['hotel', 'is_active'], name='rm_rate_hotel_active_idx'),
        ),
        migrations.AddIndex(
            model_name='roomraterule',
            index=models.Index(fields=['hotel', 'rule_type'], name='rm_rate_hotel_type_idx'),
        ),
    ]
