# Generated by Django 5.2.13 on 2026-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomhousekeepingtask_roommaintenanceincident_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='room_unique_hotel_number'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='room_type_unique_hotel_name'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='room_type_unique_hotel_code'),
        ),
    ]
