# Generated by Django 6.0.4 on 2026-05-17 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_no_active_room_overlap'),
        ('guests', '0009_remove_guest_unique_guest_identity_document_and_more'),
        ('rooms', '0005_smart_rooms'),
        ('tenancy', '0003_expand_hotelsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dayuse',
            name='actual_duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Duree reelle (h)'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant paye'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="Raison d'annulation"),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in effectue le'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out effectue le'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='converted_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_day_uses', to='bookings.booking', verbose_name='Reservation creee'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='converted_to_night',
            field=models.BooleanField(default=False, verbose_name='Converti en nuit'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_day_uses', to=settings.AUTH_USER_MODEL, verbose_name='Cree par'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin prevue day use'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='expected_duration_hours',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Duree prevue (h)'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='extension_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prolongations'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='extension_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de prolongations'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant final'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif horaire'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='no_show_reason',
            field=models.TextField(blank=True, verbose_name='Raison no-show'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depassement'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non paye'), ('partial', 'Paiement partiel'), ('paid', 'Paye'), ('refunded', 'Rembourse'), ('cancelled', 'Annule')], default='unpaid', max_length=20, verbose_name='Statut paiement'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reste a payer'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Debut day use'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sous-total'),
        ),
        migrations.AddField(
            model_name='dayuse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_day_uses', to=settings.AUTH_USER_MODEL, verbose_name='Modifie par'),
        ),
        migrations.AlterField(
            model_name='dayuse',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_payment', 'Paiement en attente'), ('ready', 'Pret a entrer'), ('in_progress', 'En cours'), ('overtime', 'Temps depasse'), ('completed', 'Termine'), ('cancelled', 'Annule'), ('no_show', 'No-show')], default='pending_payment', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='dayuse',
            index=models.Index(fields=['room', 'start_datetime'], name='dayuse_room_start_idx'),
        ),
        migrations.AddIndex(
            model_name='dayuse',
            index=models.Index(fields=['guest', 'created_at'], name='dayuse_guest_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dayuse',
            index=models.Index(fields=['payment_status'], name='dayuse_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dayuse',
            index=models.Index(fields=['end_datetime'], name='dayuse_end_idx'),
        ),
        migrations.AddIndex(
            model_name='dayuse',
            index=models.Index(fields=['check_in_at'], name='dayuse_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='dayuse',
            index=models.Index(fields=['check_out_at'], name='dayuse_checkout_idx'),
        ),
    ]
