# Generated by Django 5.2.13 on 2026-04-22 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_dayuse'),
        ('consumptions', '0001_initial'),
        ('guests', '0004_guest_client_type_guest_document_expiry_date_and_more'),
        ('rooms', '0001_initial'),
        ('stays', '0003_stay_actual_check_in_stay_actual_check_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconsumption',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='bookings.booking', verbose_name='Reservation'),
        ),
        migrations.AddField(
            model_name='clientconsumption',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='rooms.room', verbose_name='Chambre'),
        ),
        migrations.AddIndex(
            model_name='clientconsumption',
            index=models.Index(fields=['reservation', 'service_date'], name='cons_booking_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clientconsumption',
            index=models.Index(fields=['room', 'service_date'], name='cons_room_date_idx'),
        ),
    ]
