# Generated by Django 5.2.13 on 2026-04-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0002_alter_clientsatisfaction_source_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsatisfaction',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfactions', to='tenancy.hotel', verbose_name='Hotel'),
        ),
    ]
