# Generated by Django 5.2.13 on 2026-04-25 00:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("organization_created", "Organisation creee"),
                            ("organization_updated", "Organisation mise a jour"),
                            ("hotel_created", "Hotel cree"),
                            ("hotel_updated", "Hotel mis a jour"),
                            ("hotel_suspended", "Hotel suspendu"),
                            ("hotel_reactivated", "Hotel reactive"),
                            ("subscription_created", "Abonnement cree"),
                            ("subscription_updated", "Abonnement mis a jour"),
                            ("user_linked", "Utilisateur rattache"),
                            ("security_review", "Revue de securite"),
                        ],
                        max_length=40,
                        verbose_name="Type d'evenement",
                    ),
                ),
                ("target_type", models.CharField(max_length=50, verbose_name="Type de cible")),
                ("target_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="ID cible")),
                ("target_label", models.CharField(blank=True, max_length=150, verbose_name="Libelle cible")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadonnees")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Cree le")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evenement d'audit plateforme",
                "verbose_name_plural": "Evenements d'audit plateforme",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True, verbose_name="Code")),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Prix mensuel",
                    ),
                ),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Prix annuel",
                    ),
                ),
                ("max_hotels", models.PositiveIntegerField(default=1, verbose_name="Hotels maximum")),
                ("max_users", models.PositiveIntegerField(default=5, verbose_name="Utilisateurs maximum")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Cree le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mis a jour le")),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
                "ordering": ["name", "code"],
            },
        ),
        migrations.CreateModel(
            name="HotelSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("trial", "Essai"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("expired", "Expire"),
                            ("cancelled", "Annule"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Debut")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Fin")),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Fin d'essai")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuel"),
                            ("yearly", "Annuel"),
                            ("custom", "Personnalise"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Cycle de facturation",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Cree le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mis a jour le")),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription",
                        to="tenancy.hotel",
                        verbose_name="Hotel",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hotel_subscriptions",
                        to="tenancy.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hotel_subscriptions",
                        to="platform_admin.subscriptionplan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement hotel",
                "verbose_name_plural": "Abonnements hotels",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="platformauditevent",
            index=models.Index(fields=["event_type", "created_at"], name="plat_audit_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="platformauditevent",
            index=models.Index(fields=["target_type", "target_id"], name="plat_audit_target_idx"),
        ),
        migrations.AddIndex(
            model_name="platformauditevent",
            index=models.Index(fields=["created_at"], name="plat_audit_created_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(fields=["code"], name="sub_plan_code_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(fields=["is_active"], name="sub_plan_active_idx"),
        ),
        migrations.AddIndex(
            model_name="hotelsubscription",
            index=models.Index(fields=["organization", "status"], name="hotel_sub_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hotelsubscription",
            index=models.Index(fields=["plan", "status"], name="hotel_sub_plan_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hotelsubscription",
            index=models.Index(fields=["ends_at"], name="hotel_sub_ends_at_idx"),
        ),
        migrations.AddIndex(
            model_name="hotelsubscription",
            index=models.Index(fields=["trial_ends_at"], name="hotel_sub_trial_ends_idx"),
        ),
    ]
