# Generated by Django 6.0.4 on 2026-05-18 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
        ('tenancy', '0006_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditevent',
            name='event_type',
            field=models.CharField(choices=[('organization_created', 'Organisation creee'), ('organization_updated', 'Organisation mise a jour'), ('hotel_created', 'Hotel cree'), ('hotel_updated', 'Hotel mis a jour'), ('hotel_suspended', 'Hotel suspendu'), ('hotel_reactivated', 'Hotel reactive'), ('subscription_created', 'Abonnement cree'), ('subscription_updated', 'Abonnement mis a jour'), ('module_created', 'Module cree'), ('module_updated', 'Module mis a jour'), ('license_created', 'Licence creee'), ('license_updated', 'Licence mise a jour'), ('license_suspended', 'Licence suspendue'), ('license_renewed', 'Licence renouvelee'), ('admin_created', 'Admin cree'), ('admin_updated', 'Admin mis a jour'), ('admin_access_reset', 'Acces admin reinitialise'), ('user_linked', 'Utilisateur rattache'), ('security_review', 'Revue de securite')], max_length=40, verbose_name="Type d'evenement"),
        ),
        migrations.CreateModel(
            name='PlatformModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('monthly_license_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Licence mensuelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
            ],
            options={
                'verbose_name': 'Module plateforme',
                'verbose_name_plural': 'Modules plateforme',
                'ordering': ['name', 'code'],
                'indexes': [models.Index(fields=['code'], name='plat_module_code_idx'), models.Index(fields=['is_active'], name='plat_module_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspendue'), ('expired', 'Expiree'), ('cancelled', 'Annulee')], default='active', max_length=20, verbose_name='Statut')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Debut')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix mensuel applique')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_licenses', to='tenancy.hotel', verbose_name='Hotel')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_licenses', to='tenancy.organization', verbose_name='Organisation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='platform_admin.platformmodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Licence plateforme',
                'verbose_name_plural': 'Licences plateforme',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['module', 'status'], name='plat_license_module_status_idx'), models.Index(fields=['organization', 'status'], name='plat_license_org_status_idx'), models.Index(fields=['hotel', 'status'], name='plat_license_hotel_status_idx'), models.Index(fields=['ends_at'], name='plat_license_ends_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('hotel__isnull', True), ('organization__isnull', False), ('status', 'active')), fields=('module', 'organization'), name='uniq_active_org_module_license'), models.UniqueConstraint(condition=models.Q(('hotel__isnull', False), ('status', 'active')), fields=('module', 'hotel'), name='uniq_active_hotel_module_license')],
            },
        ),
    ]
