# Generated by Django 5.2.13 on 2026-04-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur plateforme'),
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(choices=[('dashboard', 'Dashboard'), ('clients', 'Clients'), ('rooms', 'Chambres'), ('operations', 'Operations'), ('billing', 'Facturation'), ('reports', 'Rapports'), ('users', 'Utilisateurs'), ('satisfaction', 'Satisfaction')], max_length=30, verbose_name='Module')),
                ('can_view', models.BooleanField(default=True, verbose_name='Voir')),
                ('can_create', models.BooleanField(default=False, verbose_name='Creer')),
                ('can_update', models.BooleanField(default=False, verbose_name='Modifier')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Supprimer')),
                ('can_manage', models.BooleanField(default=False, verbose_name='Administrer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission module utilisateur',
                'verbose_name_plural': 'Permissions modules utilisateurs',
                'indexes': [models.Index(fields=['user', 'module_code'], name='user_module_perm_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'module_code'), name='uniq_user_module_permission')],
            },
        ),
    ]
