# Generated by Django 5.2.13 on 2026-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_platform_admin_usermodulepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module_code',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('clients', 'Clients'), ('rooms', 'Chambres'), ('operations', 'Operations'), ('billing', 'Facturation'), ('reports', 'Rapports'), ('users', 'Utilisateurs'), ('satisfaction', 'Satisfaction'), ('platform_organizations', 'Plateforme organisations'), ('platform_hotels', 'Plateforme hotels'), ('platform_subscriptions', 'Plateforme abonnements'), ('platform_users', 'Plateforme utilisateurs'), ('platform_security', 'Plateforme securite')], max_length=30, verbose_name='Module'),
        ),
    ]
