# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_usermodulepermission_module_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.TextField(verbose_name="Token")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Cree le")),
            ],
            options={
                "verbose_name": "Token revoque",
                "verbose_name_plural": "Tokens revoques",
                "ordering": ["-created_at"],
            },
        ),
    ]
