# Generated by Django 6.0.4 on 2026-05-18 19:54

from django.db import migrations, models


def set_platform_role_for_existing_admins(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(is_platform_admin=True, platform_role="none").update(platform_role="super_admin_platform")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_payments_module_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(choices=[('none', 'Aucun'), ('super_admin_platform', 'Super Admin Plateforme')], default='none', max_length=30, verbose_name='Role plateforme'),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module_code',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('clients', 'Clients'), ('rooms', 'Chambres'), ('operations', 'Operations'), ('billing', 'Facturation'), ('payments', 'Paiements'), ('reports', 'Rapports'), ('history', "Journal d'activite"), ('users', 'Utilisateurs'), ('settings', 'Parametres'), ('satisfaction', 'Satisfaction'), ('platform_organizations', 'Plateforme organisations'), ('platform_hotels', 'Plateforme hotels'), ('platform_modules', 'Plateforme modules'), ('platform_licenses', 'Plateforme licences'), ('platform_subscriptions', 'Plateforme abonnements'), ('platform_users', 'Plateforme utilisateurs'), ('platform_security', 'Plateforme securite')], max_length=30, verbose_name='Module'),
        ),
        migrations.RunPython(set_platform_role_for_existing_admins, migrations.RunPython.noop),
    ]
