from django.urls import include, path

from apps.core.api_views import dashboard_summary_api, health_api, session_api
from apps.platform_admin import urls as platform_admin_urls
from apps.users.api_views import (
    change_password_api,
    csrf_api,
    email_verification_confirm_api,
    email_verification_request_api,
    forgot_password_api,
    login_api,
    logout_api,
    me_api,
    refresh_api,
    reset_password_api,
    session_detail_api,
    sessions_api,
    sessions_revoke_all_api,
    two_factor_disable_api,
    two_factor_login_verify_api,
    two_factor_setup_api,
    two_factor_verify_api,
)


urlpatterns = [
    path("health/", health_api, name="api-health"),
    path("billing/", include("apps.billing.urls")),
    path("payments/", include("apps.payments.urls")),
    path("clients/", include("apps.guests.urls")),
    path("consumptions/", include("apps.consumptions.urls")),
    path("history/", include("apps.audit_logs.api_urls")),
    path("iam/", include("apps.iam.api.urls")),
    path("operations/", include("apps.operations.urls")),
    path("platform/", include(platform_admin_urls)),
    path("reports/", include("apps.reports.api_urls")),
    path("rooms/", include("apps.rooms.urls")),
    path("settings/", include("apps.tenants.api.urls")),
    path("super-root/", include("apps.super_root.api.urls")),
    path("", include("apps.satisfaction.urls")),
    path("auth/csrf/", csrf_api, name="api-csrf"),
    path("auth/login/", login_api, name="api-login"),
    path("auth/logout/", logout_api, name="api-logout"),
    path("auth/refresh/", refresh_api, name="api-refresh"),
    path("auth/forgot-password/", forgot_password_api, name="api-auth-forgot-password"),
    path("auth/reset-password/", reset_password_api, name="api-auth-reset-password"),
    path("auth/change-password/", change_password_api, name="api-auth-change-password"),
    path("auth/email/verify/request/", email_verification_request_api, name="api-auth-email-verify-request"),
    path("auth/email/verify/confirm/", email_verification_confirm_api, name="api-auth-email-verify-confirm"),
    path("auth/2fa/setup/", two_factor_setup_api, name="api-auth-2fa-setup"),
    path("auth/2fa/verify/", two_factor_verify_api, name="api-auth-2fa-verify"),
    path("auth/2fa/login/verify/", two_factor_login_verify_api, name="api-auth-2fa-login-verify"),
    path("auth/2fa/disable/", two_factor_disable_api, name="api-auth-2fa-disable"),
    path("auth/session/", session_api, name="api-session"),
    path("auth/me/", me_api, name="api-auth-me"),
    path("auth/sessions/", sessions_api, name="api-auth-sessions"),
    path("auth/sessions/all/", sessions_revoke_all_api, name="api-auth-sessions-all"),
    path("auth/sessions/<int:session_id>/", session_detail_api, name="api-auth-session-detail"),
    path("users/", include("apps.users.urls")),
    path("dashboard/summary/", dashboard_summary_api, name="api-dashboard-summary"),
    path("day-use/", include("apps.day_use.urls")),
]
