from django.urls import include, path

from apps.core.api_views import dashboard_summary_api, health_api, session_api
from apps.operations.api_views import (
    bulk_booking_check_in_api,
    bulk_complete_cleaning_api,
    bulk_day_use_check_in_api,
    bulk_day_use_check_out_api,
    bulk_stay_check_out_api,
    booking_detail_api,
    booking_check_in_api,
    bookings_list_api,
    cancel_booking_api,
    cancel_payment_api,
    complete_room_cleaning_api,
    confirm_booking_api,
    create_booking_api,
    create_day_use_api,
    create_payment_api,
    create_stay_api,
    day_use_detail_api,
    day_use_check_in_api,
    day_use_check_out_api,
    day_uses_list_api,
    operations_choices_api,
    operations_board_api,
    payment_detail_api,
    payments_list_api,
    refund_payment_api,
    stays_list_api,
    stay_detail_api,
    stay_check_out_api,
    update_booking_api,
    update_day_use_api,
    update_payment_api,
    update_stay_api,
)
from apps.platform_admin import urls as platform_admin_urls
from apps.reports.api_views import (
    assign_default_hotel_report_api,
    day_use_report_api,
    financial_report_api,
    occupancy_report_api,
    reports_overview_api,
    tenancy_readiness_report_api,
)
from apps.users.api_views import csrf_api, login_api, logout_api, refresh_api


urlpatterns = [
    path("health/", health_api, name="api-health"),
    path("billing/", include("apps.billing.urls")),
    path("clients/", include("apps.guests.urls")),
    path("consumptions/", include("apps.consumptions.urls")),
    path("platform/", include(platform_admin_urls)),
    path("rooms/", include("apps.rooms.urls")),
    path("", include("apps.satisfaction.urls")),
    path("auth/csrf/", csrf_api, name="api-csrf"),
    path("auth/login/", login_api, name="api-login"),
    path("auth/logout/", logout_api, name="api-logout"),
    path("auth/refresh/", refresh_api, name="api-refresh"),
    path("auth/session/", session_api, name="api-session"),
    path("users/", include("apps.users.urls")),
    path("dashboard/summary/", dashboard_summary_api, name="api-dashboard-summary"),
    path("reports/overview/", reports_overview_api, name="api-reports-overview"),
    path("reports/tenancy-readiness/", tenancy_readiness_report_api, name="api-report-tenancy-readiness"),
    path(
        "reports/tenancy-readiness/assign-default-hotel/",
        assign_default_hotel_report_api,
        name="api-report-tenancy-assign-default-hotel",
    ),
    path("reports/financial/", financial_report_api, name="api-report-financial"),
    path("reports/occupancy/", occupancy_report_api, name="api-report-occupancy"),
    path("reports/day-use/", day_use_report_api, name="api-report-day-use"),
    path("operations/choices/", operations_choices_api, name="api-operations-choices"),
    path("operations/board/", operations_board_api, name="api-operations-board"),
    path("operations/bulk/bookings/check-in/", bulk_booking_check_in_api, name="api-bulk-booking-check-in"),
    path("operations/bulk/stays/check-out/", bulk_stay_check_out_api, name="api-bulk-stay-check-out"),
    path("operations/bulk/day-uses/check-in/", bulk_day_use_check_in_api, name="api-bulk-day-use-check-in"),
    path("operations/bulk/day-uses/check-out/", bulk_day_use_check_out_api, name="api-bulk-day-use-check-out"),
    path("operations/bulk/rooms/complete-cleaning/", bulk_complete_cleaning_api, name="api-bulk-complete-cleaning"),
    path("operations/bookings/", bookings_list_api, name="api-operations-bookings"),
    path("operations/bookings/<int:booking_id>/", booking_detail_api, name="api-booking-detail"),
    path("operations/bookings/create/", create_booking_api, name="api-create-booking"),
    path("operations/bookings/<int:booking_id>/update/", update_booking_api, name="api-update-booking"),
    path("operations/bookings/<int:booking_id>/confirm/", confirm_booking_api, name="api-confirm-booking"),
    path("operations/bookings/<int:booking_id>/cancel/", cancel_booking_api, name="api-cancel-booking"),
    path("operations/bookings/<int:booking_id>/check-in/", booking_check_in_api, name="api-booking-check-in"),
    path("operations/stays/", stays_list_api, name="api-operations-stays"),
    path("operations/stays/create/", create_stay_api, name="api-create-stay"),
    path("operations/stays/<int:stay_id>/", stay_detail_api, name="api-stay-detail"),
    path("operations/stays/<int:stay_id>/update/", update_stay_api, name="api-update-stay"),
    path("operations/stays/<int:stay_id>/check-out/", stay_check_out_api, name="api-stay-check-out"),
    path("operations/day-uses/", day_uses_list_api, name="api-operations-day-uses"),
    path("operations/day-uses/<int:day_use_id>/", day_use_detail_api, name="api-day-use-detail"),
    path("operations/day-uses/<int:day_use_id>/update/", update_day_use_api, name="api-update-day-use"),
    path("operations/day-use/create/", create_day_use_api, name="api-create-day-use"),
    path("operations/day-use/<int:day_use_id>/check-in/", day_use_check_in_api, name="api-day-use-check-in"),
    path("operations/day-use/<int:day_use_id>/check-out/", day_use_check_out_api, name="api-day-use-check-out"),
    path("operations/payments/", payments_list_api, name="api-operations-payments"),
    path("operations/payments/<int:payment_id>/", payment_detail_api, name="api-payment-detail"),
    path("operations/payments/<int:payment_id>/update/", update_payment_api, name="api-update-payment"),
    path("operations/payments/<int:payment_id>/refund/", refund_payment_api, name="api-refund-payment"),
    path("operations/payments/<int:payment_id>/cancel/", cancel_payment_api, name="api-cancel-payment"),
    path("operations/payments/create/", create_payment_api, name="api-create-payment"),
    path("operations/rooms/<int:room_id>/complete-cleaning/", complete_room_cleaning_api, name="api-complete-room-cleaning"),
]
