# Generated by Django 6.0.4 on 2026-05-04 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_historyentry_action_type'),
        ('tenancy', '0002_hotelsettings_checkout_payment_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=40, verbose_name='Role utilisateur')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('CONFIRM', 'Confirmation'), ('CANCEL', 'Annulation'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('PAYMENT', 'Paiement'), ('REFUND', 'Remboursement'), ('ROOM_STATUS_CHANGE', 'Changement statut chambre'), ('PRICE_CHANGE', 'Changement tarif'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('PERMISSION_CHANGE', 'Changement permission'), ('EXPORT', 'Export'), ('OTHER', 'Autre')], max_length=30, verbose_name='Action')),
                ('module', models.CharField(db_index=True, max_length=60, verbose_name='Module')),
                ('object_type', models.CharField(blank=True, max_length=80, verbose_name='Type objet')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='ID objet')),
                ('object_reference', models.CharField(blank=True, max_length=120, verbose_name='Reference objet')),
                ('description', models.TextField(verbose_name='Description')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Nouvelles valeurs')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadonnees')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navigateur')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Succes'), ('warning', 'Avertissement'), ('danger', 'Danger'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Gravite')),
                ('session_key', models.CharField(blank=True, max_length=80, verbose_name='Session')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cree le')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tenancy.hotel', verbose_name='Hotel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activite",
                'verbose_name_plural': "Journal d'activite",
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_sensitive_activitylog', 'Can view sensitive activity logs'), ('export_activitylog', 'Can export activity logs')],
                'indexes': [models.Index(fields=['hotel', 'created_at'], name='activity_hotel_created_idx'), models.Index(fields=['hotel', 'module'], name='activity_hotel_module_idx'), models.Index(fields=['action', 'severity'], name='activity_action_severity_idx'), models.Index(fields=['user', 'created_at'], name='activity_user_created_idx')],
            },
        ),
    ]
