# Generated by Django 5.2.13 on 2026-04-22 12:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_day_use'),
        ('bookings', '0002_dayuse'),
        ('consumptions', '0002_clientconsumption_reservation_clientconsumption_room_and_more'),
        ('guests', '0004_guest_client_type_guest_document_expiry_date_and_more'),
        ('rooms', '0001_initial'),
        ('stays', '0003_stay_actual_check_in_stay_actual_check_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Emise'), ('partially_paid', 'Partiellement payee'), ('paid', 'Payee'), ('cancelled', 'Annulee')], default='draft', max_length=20, verbose_name='Statut')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Emise le')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'echeance")),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sous-total')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remise')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxe')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant paye')),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Solde restant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('stay_folio', 'Folio de sejour'), ('service_batch', 'Lot de services'), ('consumptions', 'Selection de consommations'), ('other', 'Autre')], default='manual', max_length=20, verbose_name='Origine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='guests.guest', verbose_name='Client')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invoices_issued', to=settings.AUTH_USER_MODEL, verbose_name='Emise par')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bookings.booking', verbose_name='Reservation')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='stays.stay', verbose_name='Sejour')),
            ],
            options={
                'verbose_name': 'Facture client',
                'verbose_name_plural': 'Factures clients',
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.clientinvoice', verbose_name='Facture'),
        ),
        migrations.CreateModel(
            name='ClientInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Libelle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantite')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant ligne')),
                ('service_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de service')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='consumptions.clientconsumption', verbose_name='Consommation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.clientinvoice', verbose_name='Facture')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='rooms.room', verbose_name='Chambre')),
                ('service_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='consumptions.servicedepartment', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Ligne de facture client',
                'verbose_name_plural': 'Lignes de facture client',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['client', 'issued_at'], name='invoice_client_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['stay', 'issued_at'], name='invoice_stay_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['reservation', 'issued_at'], name='invoice_booking_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='invoice_amount_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance_due__gte', 0)), name='invoice_balance_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='invoice_item_total_non_negative'),
        ),
    ]
