# Generated by Django 5.2.13 on 2026-04-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_payment_client_and_type(apps, schema_editor):
    Payment = apps.get_model('billing', 'Payment')

    for payment in Payment.objects.select_related('booking', 'stay', 'day_use', 'invoice').all():
        client_id = payment.client_id
        if not client_id:
            if payment.invoice_id:
                client_id = payment.invoice.client_id
            elif payment.stay_id:
                client_id = payment.stay.guest_id
            elif payment.booking_id:
                client_id = payment.booking.guest_id
            elif payment.day_use_id:
                client_id = payment.day_use.guest_id

        payment_type = payment.payment_type or 'partial'
        if payment.status == 'refunded':
            payment_type = 'refund'
        elif payment.invoice_id:
            balance_due = payment.invoice.balance_due or 0
            payment_type = 'full' if payment.amount >= balance_due and balance_due > 0 else 'partial'
        elif payment.booking_id and not payment.stay_id:
            payment_type = 'advance'

        Payment.objects.filter(pk=payment.pk).update(
            client_id=client_id,
            payment_type=payment_type,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_clientinvoice_payment_invoice_clientinvoiceitem_and_more'),
        ('bookings', '0002_dayuse'),
        ('guests', '0004_guest_client_type_guest_document_expiry_date_and_more'),
        ('stays', '0003_stay_actual_check_in_stay_actual_check_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='guests.guest', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, max_length=80, verbose_name='Reference externe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Avance'), ('partial', 'Paiement partiel'), ('full', 'Paiement complet'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement')], default='partial', max_length=20, verbose_name='Type de paiement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Enregistre par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(blank=True, max_length=30, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Especes'), ('card', 'Carte'), ('transfer', 'Virement'), ('mobile_money', 'Mobile money'), ('cheque', 'Cheque'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.RunPython(backfill_payment_client_and_type, noop_reverse),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'paid_at'], name='payment_client_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stay', 'paid_at'], name='payment_stay_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'paid_at'], name='payment_invoice_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payment_status_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'paid_at'], name='payment_method_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'paid_at'], name='payment_type_paid_idx'),
        ),
    ]
