# Generated by Django 5.2.13 on 2026-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_clientinvoice_hotel_payment_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('invoice_payment', 'Paiement facture'), ('advance', 'Avance'), ('deposit', 'Depot / caution'), ('credit_topup', 'Recharge credit client'), ('day_use_prepayment', 'Prepaiement day use'), ('partial', 'Paiement partiel'), ('full', 'Paiement complet'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement')], default='partial', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
