# Generated by Django 5.2.13 on 2026-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guest',
            name='unique_guest_identity_document',
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('identity_document_type', ''), _negated=True), models.Q(('identity_document_number', ''), _negated=True)), fields=('identity_document_type', 'identity_document_number'), name='unique_guest_identity_document'),
        ),
    ]
