# Generated by Django 5.2.13 on 2026-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_phone_constraint_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individuel'), ('company', 'Entreprise'), ('vip', 'VIP'), ('corporate', 'Corporate')], default='individual', max_length=20, verbose_name='Type de client'),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'emission"),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_issue_place',
            field=models.CharField(blank=True, max_length=150, verbose_name="Lieu d'emission"),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Contact d'urgence"),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Telephone d'urgence"),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lien avec le client'),
        ),
        migrations.AddField(
            model_name='guest',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Celibataire'), ('married', 'Marie(e)'), ('divorced', 'Divorce(e)'), ('widowed', 'Veuf(ve)'), ('other', 'Autre')], max_length=20, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='guest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autres prenoms'),
        ),
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalite'),
        ),
        migrations.AddField(
            model_name='guest',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='guest',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='guest',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone secondaire'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='identity_document_type',
            field=models.CharField(blank=True, choices=[('national_id', "Carte nationale d'identite"), ('passport', 'Passeport'), ('residence_permit', 'Titre de sejour'), ('driver_license', 'Permis de conduire'), ('other', 'Autre')], max_length=30, verbose_name='Type de piece'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email'], name='guest_email_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['client_type'], name='guest_type_idx'),
        ),
    ]
