# Generated by Django 6.0.4 on 2026-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_remove_guest_country'),
        ('tenancy', '0003_expand_hotelsettings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guest',
            name='unique_guest_identity_document',
        ),
        migrations.RemoveConstraint(
            model_name='guest',
            name='unique_guest_phone',
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('hotel', 'phone'), name='unique_guest_phone_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('identity_document_type', ''), _negated=True), models.Q(('identity_document_number', ''), _negated=True)), fields=('hotel', 'identity_document_type', 'identity_document_number'), name='unique_guest_identity_document_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('hotel', 'email'), name='unique_guest_email_per_hotel'),
        ),
    ]
