# Generated by Django 6.0.4 on 2026-05-22 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stays', '0006_alter_stay_adults_count_alter_stay_children_count'),
        ('tenancy', '0006_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_remise', models.CharField(choices=[('pct', 'Pourcentage'), ('fixe', 'Montant fixe')], default='pct', max_length=10)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('permission_requise', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['restaurant__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pos_restaurant.menu')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disponible', models.BooleanField(default=True)),
                ('temps_prep_min', models.PositiveIntegerField(default=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pos/menu/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_restaurant.menucategory')),
            ],
            options={
                'ordering': ['category__ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cuisine', 'En cuisine'), ('servie', 'Servie'), ('payee', 'Payee'), ('annulee', 'Annulee')], default='ouverte', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_prep', 'En preparation'), ('pret', 'Pret'), ('livre', 'Livre')], default='nouveau', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('cuisinier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='pos_restaurant.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remise_montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxe_montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('payee', 'Payee'), ('annulee', 'Annulee')], default='ouverte', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_restaurant.discount')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='pos_restaurant.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('especes', 'Especes'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('chambre', 'Ajouter a la chambre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_externe', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos_restaurant.bill')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_payments_processed', to=settings.AUTH_USER_MODEL)),
                ('sejour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_payments', to='stays.stay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='tenancy.hotel')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='pos_restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='discount',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='pos_restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='pos_restaurant.restaurant')),
            ],
            options={
                'ordering': ['restaurant__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('capacite', models.PositiveIntegerField(default=4)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupee'), ('reservee', 'Reservee'), ('fermee', 'Fermee')], default='libre', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pos_restaurant.diningarea')),
            ],
            options={
                'ordering': ['area__nom', 'numero'],
                'unique_together': {('area', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos_restaurant.table'),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taux_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='pos_restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='VoidReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_reasons', to='pos_restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_prep', 'En preparation'), ('pret', 'Pret'), ('servi', 'Servi'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_restaurant.order')),
                ('void_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_restaurant.voidreason')),
            ],
        ),
    ]
