# Generated by Django 6.0.4 on 2026-05-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_restaurant', '0002_menuitem_timestamps_image_help'),
        ('tenancy', '0006_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_role', models.CharField(choices=[('manager_restaurant', 'Manager restaurant'), ('caissier', 'Caissier'), ('serveur', 'Serveur'), ('cuisinier', 'Cuisinier'), ('barman', 'Barman')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_accesses_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_user_accesses', to='tenancy.hotel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_user_accesses', to='tenancy.organization')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='pos_restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hotel__name', 'restaurant__nom', 'user__username'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='pos_access_user_active_idx'), models.Index(fields=['hotel', 'is_active'], name='pos_access_hotel_active_idx'), models.Index(fields=['restaurant', 'is_active'], name='pos_access_rest_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('restaurant__isnull', False)), fields=('user', 'restaurant'), name='uniq_pos_access_user_restaurant'), models.UniqueConstraint(condition=models.Q(('restaurant__isnull', True)), fields=('user', 'hotel'), name='uniq_pos_access_user_hotel')],
            },
        ),
    ]
