# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_restaurant", "0003_userposaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POSServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(blank=True, max_length=80)),
                ("code", models.CharField(max_length=40)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Actif"), ("suspended", "Suspendu"), ("inactive", "Inactif")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servers",
                        to="pos_restaurant.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_server_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["restaurant__nom", "first_name", "last_name"],
                "indexes": [
                    models.Index(fields=["restaurant", "status"], name="pos_server_rest_status_idx"),
                    models.Index(fields=["user", "status"], name="pos_server_user_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("restaurant", "code"), name="uniq_pos_server_restaurant_code"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServerShift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shift_name", models.CharField(max_length=120)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Ouvert"), ("closed", "Cloture"), ("cancelled", "Annule")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_shifts",
                        to="pos_restaurant.restaurant",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="pos_restaurant.posserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(fields=["server", "status"], name="pos_shift_server_status_idx"),
                    models.Index(fields=["restaurant", "status"], name="pos_shift_rest_status_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pos_restaurant.posserver",
            ),
        ),
    ]
