from django.urls import path

from apps.super_root.api.views import (
    super_root_audit_logs_api,
    super_root_auth_login_api,
    super_root_auth_logout_api,
    super_root_backups_api,
    super_root_dashboard_api,
    super_root_hotel_audit_export_api,
    super_root_hotel_audit_logs_api,
    super_root_hotel_billing_api,
    super_root_hotel_detail_api,
    super_root_hotel_maintenance_api,
    super_root_hotel_modules_api,
    super_root_hotel_monitoring_api,
    super_root_hotel_reactivate_api,
    super_root_hotel_security_api,
    super_root_hotel_suspend_api,
    super_root_hotels_api,
    super_root_licenses_api,
    super_root_maintenance_api,
    super_root_maintenance_run_api,
    super_root_monitoring_api,
    super_root_monitoring_live_api,
    super_root_modules_api,
    super_root_organizations_api,
    super_root_platform_api,
    super_root_platform_action_api,
    super_root_platforms_api,
    super_root_platform_snapshot_export_api,
    super_root_permissions_api,
    super_root_roles_api,
    super_root_security_api,
    super_root_security_alerts_api,
    super_root_security_session_revoke_api,
    super_root_system_settings_api,
    super_root_users_api,
)


urlpatterns = [
    path("auth/login/", super_root_auth_login_api, name="api-super-root-auth-login"),
    path("auth/logout/", super_root_auth_logout_api, name="api-super-root-auth-logout"),
    path("dashboard/", super_root_dashboard_api, name="api-super-root-dashboard"),
    path("platform/", super_root_platform_api, name="api-super-root-platform"),
    path("platforms/", super_root_platforms_api, name="api-super-root-platforms"),
    path("platforms/<slug:platform_id>/snapshot/export/", super_root_platform_snapshot_export_api, name="api-super-root-platform-snapshot-export"),
    path("platforms/<slug:platform_id>/<str:action>/", super_root_platform_action_api, name="api-super-root-platform-action"),
    path("organizations/", super_root_organizations_api, name="api-super-root-organizations"),
    path("hotels/", super_root_hotels_api, name="api-super-root-hotels"),
    path("hotels/<int:hotel_id>/", super_root_hotel_detail_api, name="api-super-root-hotel-detail"),
    path("hotels/<int:hotel_id>/modules/", super_root_hotel_modules_api, name="api-super-root-hotel-modules"),
    path("hotels/<int:hotel_id>/security/", super_root_hotel_security_api, name="api-super-root-hotel-security"),
    path("hotels/<int:hotel_id>/billing/", super_root_hotel_billing_api, name="api-super-root-hotel-billing"),
    path("hotels/<int:hotel_id>/monitoring/", super_root_hotel_monitoring_api, name="api-super-root-hotel-monitoring"),
    path("hotels/<int:hotel_id>/audit-logs/", super_root_hotel_audit_logs_api, name="api-super-root-hotel-audit-logs"),
    path("hotels/<int:hotel_id>/audit-logs/export/", super_root_hotel_audit_export_api, name="api-super-root-hotel-audit-export"),
    path("hotels/<int:hotel_id>/suspend/", super_root_hotel_suspend_api, name="api-super-root-hotel-suspend"),
    path("hotels/<int:hotel_id>/reactivate/", super_root_hotel_reactivate_api, name="api-super-root-hotel-reactivate"),
    path("hotels/<int:hotel_id>/maintenance/", super_root_hotel_maintenance_api, name="api-super-root-hotel-maintenance"),
    path("users/", super_root_users_api, name="api-super-root-users"),
    path("roles/", super_root_roles_api, name="api-super-root-roles"),
    path("permissions/", super_root_permissions_api, name="api-super-root-permissions"),
    path("licenses/", super_root_licenses_api, name="api-super-root-licenses"),
    path("modules/", super_root_modules_api, name="api-super-root-modules"),
    path("audit-logs/", super_root_audit_logs_api, name="api-super-root-audit-logs"),
    path("security/", super_root_security_api, name="api-super-root-security"),
    path("security/sessions/<int:session_id>/", super_root_security_session_revoke_api, name="api-super-root-security-session-revoke"),
    path("security-alerts/", super_root_security_alerts_api, name="api-super-root-security-alerts"),
    path("system-settings/", super_root_system_settings_api, name="api-super-root-system-settings"),
    path("maintenance/", super_root_maintenance_api, name="api-super-root-maintenance"),
    path("maintenance/run/", super_root_maintenance_run_api, name="api-super-root-maintenance-run"),
    path("monitoring/live/", super_root_monitoring_live_api, name="api-super-root-monitoring-live"),
    path("monitoring/", super_root_monitoring_api, name="api-super-root-monitoring"),
    path("backups/", super_root_backups_api, name="api-super-root-backups"),
]
